### ISSUE TITLE
Tester confusion

### ISSUE THREAD

**Issue by omeh-a** [au-ts/ipbench#4]
Testers will sometimes fail to reset properly; especially if tests are interrupted. This results in the need to run an explicit stop command on every tester for safety between consecutive tests.

Testers should automatically do this when a new test begins, and more crucially as soon as their target stops returning packets as expected.

**Comment by wom-bat** [comment]
You can do this with the `-r` flag to ipbench

**Comment by omeh-a** [comment]
No issue in that case. This does help the case for #10 because a lot of people don't know about this - e.g. Ivan has been using a `stopbench` script which telnets into each machine and explicitly stops.
